version: "2"
services:
  web:
    image: node:5.11.1
    ports:
      - "3000:3000"
    user: 'nodejs'
    command: ['/usr/bin/dumb-init', 'node', '/home/nodejs/app/index.js']
    links:
      - redis

  redis:
    image: redis:3.2.0

registries: {}